# Copyright 2018 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#FROM ARG_FROM_IPT
FROM lcr.loongnix.cn/k8s-build-image/debian-iptables:buster-v1.3.0
#ADD bin/ARG_ARCH/ARG_BIN /ARG_BIN
ADD .go/bin/node-cache /node-cache
EXPOSE 53 53/udp
EXPOSE 53 53/tcp
ENTRYPOINT ["/node-cache"]
